import Footer from '@/components/layout/Footer';
import Header from '@/components/layout/Header';
import NavBar from '@/components/layout/NavBar';
import '@fortawesome/fontawesome-free/css/all.min.css';
import { Poppins, Roboto } from 'next/font/google';
import "./globals.css";

const poppins = Poppins(
  {
    subsets: ["latin"],
    display: 'swap',
    weight: ['400', '500', '600', '700'],
  }
)
const roboto = Roboto(
  {
    subsets: ["latin"],
    display: 'swap',
    weight: ['400', '500', '700'],
  }
);


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body >
        <Header />
        <NavBar />
        {children}

        <Footer />
      </body>
    </html>
  );
}
