import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import NavBar from "@/components/layout/NavBar";
import AppContextProvider from "@/context";
import "@fortawesome/fontawesome-free/css/all.min.css";
import { SessionProvider } from "next-auth/react";
import { Poppins, Roboto } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const poppins = Poppins({
    subsets: ["latin"],
    display: "swap",
    weight: ["400", "500", "600", "700"],
});
const roboto = Roboto({
    subsets: ["latin"],
    display: "swap",
    weight: ["400", "500", "700"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="selection:bg-primary selection:text-white">
                <SessionProvider>
                    <AppContextProvider>
                        <Header />
                        <NavBar />
                        {children}
                        <Footer />
                    </AppContextProvider>
                </SessionProvider>
                <ToastContainer position="bottom-center" limit={2} />
            </body>
        </html>
    );
}
